name: Deploy Frontend to AWS EC2

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm install

    - name: Compilar Angular (Producción)
      run: npm run build

    - name: Enviar archivos al servidor (SCP)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "dist/front-angular/*"
        target: "~/"

    - name: Reemplazar archivos y reiniciar Nginx (SSH)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo rm -rf /var/www/html/*
          sudo cp -a ~/dist/front-angular/browser/. /var/www/html/
          sudo mv /var/www/html/index.csr.html /var/www/html/index.html
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html
          sudo systemctl restart nginx
